### ISSUE TITLE
Text content not visible

### ISSUE THREAD

**Issue by vulovix** [nienow/sn-mermaid#87]
I've installed extension but the problem exists with the displaying text elements. For example on gant, mindmap, pie, git, quadrant text is visible, but on other types like flow, class, state, user journey its invisible for some reason. 
Im on version 3.195.3 on desktop app, but the problem also appears on the demo page: https://nienow.github.io/sn-mermaid/demo.html.

**Comment by nienow** [comment]
Thank you for reporting this. It seems like something went wrong with the last build/deployment. And it appears to be working again after a fresh deployment.
